### ISSUE TITLE
CLIP text embedding substraction

### ISSUE THREAD

**Issue by ivanprado** [InstantStyle/InstantStyle#6]
Hi! Great work!

I'm having trouble locating in your code where you subtract the CLIP text embedding from the CLIP image embedding in the IPAdapter, and where can you pass the prompt you want to be subtracted to the pipeline. Can you help? 

Thank you! :-)

**Comment by ResearcherXman** [comment]
Check [here](https://github.com/InstantStyle/InstantStyle/blob/main/ip_adapter/ip_adapter.py#L161).

**Comment by ivanprado** [comment]
Thank you! And the parameters are `neg_content_prompt` and `neg_content_scale`. Thank you!
